name: Benchmarks
on:
  push:
    branches: [ next ]

permissions:
  checks: write

jobs:
  build:
    name: Benchmarks
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v5

    - name: Install Pre-requisits on ubuntu
      run: |
        sudo apt-get -qy update
        sudo apt-get install g++ ninja-build cmake
        ninja --version
        cmake --version
        g++ --version

    - name: Configure
      run: >
        cmake -S . -B build-rel -G Ninja
        -DCMAKE_BUILD_TYPE=Release
        -DRETICULA_BUILD_BENCHMARKS=on
        -DRETICULA_BUILD_TESTS=off

    - name: Build
      run: cmake --build build-rel --config Release --target reticula_benchmarks -j 4 --verbose

    - name: Run benchmarks and send to Benchboard
      uses: arashbm/benchboard-client@v0.0.2
      with:
        project: 'reticula'
        benchmark-command: './build-rel/benchmark --benchmark_format=json --benchmark_filter=.*'
        token: ${{ secrets.BENCHBOARD_TOKEN }}
        machine-name: 'gh-action-ubuntu-24.04'
        endpoint: "https://benchboard.fly.dev"
