name: Python Tests
on: [push, pull_request]

jobs:
  build:
    name: Python Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux-intel
            runs-on: ubuntu-latest
            arch: x86_64
          - os: linux-arm
            runs-on: ubuntu-24.04-arm
            arch: aarch64
          - os: windows-intel
            runs-on: windows-latest
            arch: AMD64
          - os: windows-arm
            runs-on: windows-11-arm
            arch: ARM64
          - os: macos-intel
            runs-on: macos-latest
            arch: x86_64
          - os: macos-arm
            runs-on: macos-latest
            arch: arm64
          - os: pyodide-wasm32
            runs-on: ubuntu-latest
            platform: pyodide
            arch: wasm32

    steps:
    - uses: actions/checkout@v5

    - name: Build wheels
      uses: pypa/cibuildwheel@v3.1.4
      env:
        CIBW_PLATFORM: ${{ matrix.platform || 'auto' }}
        CIBW_ARCHS: ${{ matrix.arch }}
      with:
        package-dir: python

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
        path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build sdist
        run: pipx run build ./python --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: python/dist/*.tar.gz
