name: Tests
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install GCC 10
      run: |
        sudo apt-get -qy update
        sudo apt-get install g++-11
    - uses: actions/checkout@v2
    - name: g++ version
      run: g++-11 -v
    - name: cmake build
      env:
        CC: g++-11
        CXX: g++-11
      run: |
        mkdir build
        cmake -Bbuild -H.
        cmake --build build/ --target dag_tests -j 2
    - name: Run tests
      run: build/dag_tests
