name: Tests
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install GCC
      run: |
        sudo apt-get -qy update
        sudo apt-get install gcc-10 g++-10
    - uses: actions/checkout@v2
    - name: g++ version
      run: g++-10 -v
    - name: cmake build
      env:
        CC: g++-10
        CXX: g++-10
      run: |
        mkdir build
        cmake -Bbuild -H.
        cmake --build build/ --target reticula_tests -j 2
    - name: Run tests
      run: build/reticula_tests
