name: Tests
on: [push, pull_request]

jobs:
  build:
    name: Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-15]

    steps:
    - name: Install Pre-requisits on ubuntu
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      run: |
        sudo apt-get -qy update
        sudo apt-get install g++ ninja-build cmake
        ninja --version
        cmake --version
        g++ --version

    - name: Install dependencies on windows
      if: ${{ startsWith(matrix.os, 'windows') }}
      run: |
        choco install ninja cmake --no-progress
        cmake --version

    - uses: actions/checkout@v4

    - name: cmake build
      run: |
        mkdir build
        cmake -Bbuild -S. -DCMAKE_BUILD_TYPE=Release
        cmake --build build/ --target reticula_tests -j 2 --verbose --config=Release

    - name: Run tests
      working-directory: build
      run: ctest -C Release --output-on-failure -j 2
