name: Tests
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install GCC 10
      run: |
        sudo apt-get -qy update
        sudo apt-get install g++-10
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: g++ version
      run: g++-10 -v
    - name: Run tests
      run: make CXX=g++-10 check
