name: Tests
on: [push, pull_request]

jobs:
  build:
    name: Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]

    steps:
    - name: Install Pre-requisits on ubuntu
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      run: |
        sudo apt-get -qy update
        sudo apt-get install g++ ninja-build cmake
        ninja --version
        cmake --version
        g++ --version

    - name: Install dependencies on windows
      if: ${{ startsWith(matrix.os, 'windows') }}
      run: |
        choco install ninja cmake
        cmake --version

    - uses: actions/checkout@v3

    - name: cmake build (macos)
      if: ${{ startsWith(matrix.os, 'macos') }}
      run: |
        mkdir build
        sudo xcode-select -s "/Applications/Xcode_14.2.app"
        cmake -Bbuild -S.
        cmake --build build/ --target reticula_tests -j 3 --verbose

    - name: cmake build
      if: ${{ !startsWith(matrix.os, 'macos') }}
      run: |
        mkdir build
        cmake -Bbuild -S.
        cmake --build build/ --target reticula_tests -j 2 --verbose

    - name: Run tests
      working-directory: build
      run: ctest -C Debug --output-on-failure -j 2
